name: Deploy with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop old containers
        run: |
          sudo docker stop backend-container || true
          sudo docker stop frontend-container || true
          sudo docker rm backend-container || true
          sudo docker rm frontend-container || true

      - name: Build backend image
        run: |
          cd backend
          sudo docker build -t backend-app .

      - name: Build frontend image
        run: |
          cd frontend
          sudo docker build -t frontend-app .

      - name: Create backend env file
        run: |
          cat > backend/.env << EOF
          DB_HOST=172.17.0.1
          DB_USER=cruduser
          DB_PASSWORD=Password@123
          DB_DATABASE=crud_operations
          DB_TABLENAME=users
          EOF

      - name: Run backend container
        run: |
          sudo docker run -d \
            --name backend-container \
            -p 3000:3000 \
            --env-file backend/.env \
            backend-app

      - name: Run frontend container
        run: |
          sudo docker run -d \
            --name frontend-container \
            -p 5000:5000 \
            frontend-app

      - name: Check running containers
        run: sudo docker ps
